# Generated by Django 4.1.5 on 2023-01-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='outoff',
            new_name='outof',
        ),
    ]
