# Generated by Django 4.1.5 on 2023-01-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_game', '0002_rename_outoff_status_outof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='computerSelection',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
